services:
  taxi-web:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
        VITE_WS_URL: ${VITE_WS_URL:-}
        VITE_USE_MOCK_API: ${VITE_USE_MOCK_API:-false}
        VITE_YANDEX_MAPS_API_KEY: ${VITE_YANDEX_MAPS_API_KEY:-}
        VITE_WS_DEBUG: ${VITE_WS_DEBUG:-false}
    image: registry.dev.it59com.ru/taxi-platform/taxi-web:latest
    ports:
      - "5173:80"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/v1}
      VITE_WS_URL: ${VITE_WS_URL:-}
      VITE_USE_MOCK_API: ${VITE_USE_MOCK_API:-false}
      VITE_YANDEX_MAPS_API_KEY: ${VITE_YANDEX_MAPS_API_KEY:-}
      VITE_WS_DEBUG: ${VITE_WS_DEBUG:-false}
