services:
  taxi-web:
    build:
      context: .
    image: registry.dev.it59com.ru/taxi-platform/taxi-web:latest
    ports:
      - "5173:80"
    environment:
      - VITE_API_BASE_URL=https://taxi.wkfc.online/api/v1
      - VITE_WS_URL=wss://taxi.wkfc.online/ws
